//POST ACTION TYPE
export const FETCH_POST = "FETCH_POST";
export const CREATE_POST = "CREATE_POST";
export const DELETE_POST = "DELETE_POST";
export const UPDATE_POST = "UPDATE_POST";
export const FIND_POST_BY_ID = "FIND_POST_BY_ID";

//REGISTER ACTION TYPE
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

//LOGIN ACTION TYPE
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

//COMMENT ACTION TYPE
export const FIND_COMMENT_BY_POST_ID = "FIND_COMMENT_BY_POST_ID";
export const FIND_COMMENT_FAIL = "FIND_COMMENT_FAIL";
export const POST_COMMENT = "POST_COMMENT";

//LIKE ACTION TYPE
export const LIKE_POST = "LIKE_POST";
export const DISLIKE_POST = "DISLIKE_POST";

//FILE ACTION TYPE
export const UPLOAD_IMAGE = "UPLOAD_IMAGE";


