export const FETCH_POST = "FETCH_POST";
export const CREATE_POST = "CREATE_POST";
export const FIND_POST_BY_ID = "FIND_POST_BY_ID";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const FIND_COMMENT_BY_POST_ID = "FIND_COMMENT_BY_POST_ID";
export const FIND_COMMENT_FAIL = "FIND_COMMENT_FAIL";
export const POST_COMMENT = "POST_COMMENT";


